# Fly.io launch config for @bomberman/api
# Adjust app name on first `fly launch`.
app = "bomberman-api"
primary_region = "gru"

[build]
  dockerfile = "Dockerfile"

[env]
  NODE_ENV = "production"
  PORT = "3333"
  LOG_LEVEL = "info"
  COOKIE_SECURE = "true"
  JWT_ACCESS_TTL_SECONDS = "900"
  JWT_REFRESH_TTL_DAYS = "30"

[http_service]
  internal_port = 3333
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

  [http_service.concurrency]
    type = "requests"
    soft_limit = 200
    hard_limit = 250

[[vm]]
  size = "shared-cpu-1x"
  memory = "512mb"
  cpu_kind = "shared"
  cpus = 1
